### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'max_n'

### ISSUE THREAD

**Issue by mattdmem** [TimD1/nPoRe#1]
Hello - Any ideas what is causing this error?

```
> calculating confusion matrices
    0 of 45 chunks processedmultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/Matt.Parker/wc/miniconda3/envs/epi2melabs-wf-tb-amr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/Matt.Parker/wc/miniconda3/envs/epi2melabs-wf-tb-amr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "src/bam.pyx", line 353, in bam.calc_confusion_matrices
  File "src/bam.pyx", line 362, in bam.calc_confusion_matrices
AttributeError: 'NoneType' object has no attribute 'max_n'
"""
```
Thanks

Matt

**Comment by TimD1** [comment]
`max_n` is stored as an attribute of the global variable `cfg.args`, which for some reason in your case  seems to be `None`. `cfg.args` is set unconditionally after the arguments are parsed... How exactly are you invoking `realign.py`?

**Comment by mattdmem** [comment]
I also tried passing it as an arg but I get the same issue.

I'm invoking by following the instructions on the README!

**Comment by TimD1** [comment]
Thanks for bringing this to my attention; I'm looking into it right now. 

I'm trying to reproduce the error using a fresh clone, but not having much luck. It looks like your error occurs while recalculating the confusion matrices. If `--stats_dir` is provided as shown in the README, then the confusion matrices shouldn't be recalculated, unless something else is wrong. 

Can you please paste exactly the command you used, and any relevant information about your environment? In any case, I'll create a Docker setup this afternoon, which should work for you.

**Comment by mattdmem** [comment]
Ha - now I say I followed the instructions but not the `--stats_dir` - including this solves this message - I still don't have success but I will raise another issue
