### ISSUE TITLE
Clair3 scripts and modifications

### ISSUE THREAD

**Issue by ftostevin** [TimD1/nPoRe#3]
Thanks for sharing this very interesting realignment approach.

I noticed that your `scripts/realign_pipeline.sh` scripts refers to some model training scripts in the `./clair3/` folder that I could not find in the repository. Would you mind sharing these scripts as well?
Also, could you provide more details of the corresponding modifications that you made to Clair3, particularly the haplotype-phased pileup calling (`clair3-hap`) that you describe in your preprint?

**Comment by TimD1** [comment]
Sure, I should be able to add the `clair3` training scripts to the repo this afternoon. They're mostly the same ones provided in the original Clair3 repo, with some minor changes.

I can also upload the modified Clair3 (`clair-hap`) as a separate repo. The only real change is that the input tensor is of size 3*original, segregated by haplotype (1,2,unphased). I had to sort/split the input BAM, parse them in parallel, then propagate the size changes throughout the code, but that's pretty much it.

**Comment by ftostevin** [comment]
> Sure, I should be able to add the `clair3` training scripts to the repo this afternoon. They're mostly the same ones provided in the original Clair3 repo, with some minor changes.

Great

> I can also upload the modified Clair3 (`clair-hap`) as a separate repo. The only real change is that the input tensor is of size 3*original, segregated by haplotype (1,2,unphased). I had to sort/split the input BAM, parse them in parallel, then propagate the size changes throughout the code, but that's pretty much it.

That sounds like what I understood from the text. So whereas the original pileup input was of shape (33 positions, 18 features), the new input is of shape (33, 54) with one set of features for each haplotype? Is filtering of sites on depth, allele fractions, etc. still done on the overall counts or per haplotype?

**Comment by TimD1** [comment]
Closing due to our prior email chain; feel free to re-open if you still have questions.
