### ISSUE TITLE
Maximum recommended homopolymer length? 

### ISSUE THREAD

**Issue by palakpsheth** [TimD1/nPoRe#4]
I am analyzing a sample with long homopolymer runs. What are the maximum recommended values for  `max_n` and `max_l` ?

Thanks!

**Comment by TimD1** [comment]
`n` is for controlling the maximum repeat unit length which is assigned a custom penalty, anywhere from 6-10 should be fine. If you only care about homopolymers, you can set it even lower.

`l` controls the maximum length (number of repeats) for which statistics are collected and the penalty for differing length continues to decrease. In other words, if you have `max_l` of 100, then deleting 20 bases from a HP of length 100 will have the same penalty as deleting 20 bases from a HP of length 150 or 400. It shouldn't affect the alignment results much at all. Anything above 20 should be fine, and I don't think there's much benefit going over 100.

**Comment by palakpsheth** [comment]
Great thanks
